CREATE TABLE PLYTY_DVD (
ID_PLYTY INT NOT NULL PRIMARY KEY,
TYTUL VARCHAR(100),
REZYSER VARCHAR(50),
ROK_WYDANIA DATE,
GATUNEK VARCHAR(20),
CENA_ZA_WYPOZYCZENIE DECIMAL(10,2)
);
CREATE TABLE KLIENCI(
ID_KLIENT INT PRIMARY KEY,
IMIE VARCHAR(30),
NAZWISKO VARCHAR(30),
ADRES VARCHAR(50),
NUMER_TEL VARCHAR(11),
EMAIL VARCHAR(30)
);
CREATE TABLE RACHUNKI(
ID_RACHUNKI INT PRIMARY KEY,
DATA_WYSTAWINIA DATE,
OPLATA DECIMAL(10,2),
ID_KLIENT INT
);
ALTER TABLE RACHUNKI ADD FOREIGN KEY (ID_KLIENT) REFERENCES KLIENCI(ID_KLIENT);

CREATE TABLE ZAMOWIENIA(
ID_ZAMOWIENIA INT PRIMARY KEY,
ID_KLIENT INT,
ID_PLYTY INT,
DATA_ZAMOWIENIA DATE,
DATA_ODBIORU DATE,
DATA_ZWOROTU_PLANOWANA DATE,
OPLATA DECIMAL(10,3)
);
ALTER TABLE ZAMOWIENIA ADD FOREIGN KEY (ID_KLIENT) REFERENCES KLIENCI(ID_KLIENT);
ALTER TABLE ZAMOWIENIA ADD FOREIGN KEY (ID_PLYTY) REFERENCES PLYTY_DVD(ID_PLYTY);
CREATE TABLE OPINIE_KLIENTOW(
  ID_OPINII INT PRIMARY KEY,
  ID_KLIENT INT,
  ID_PLYTY INT,
  OCENA INT,
  TRESC VARCHAR(255),
  FOREIGN KEY (ID_KLIENT) REFERENCES KLIENCI(ID_KLIENT),
  FOREIGN KEY (ID_PLYTY) REFERENCES PLYTY_DVD(ID_PLYTY)
);
CREATE TABLE WYPOZYCZENIA(
ID_WYPOZYCZENIA INT PRIMARY KEY,
DATA_WYPOZYCZENIA DATE,
DATA_ZWROTU DATE, 
OPLATA DECIMAL(10,2),
ID_KLIENT INT,
FOREIGN KEY (ID_KLIENT) REFERENCES KLIENCI(ID_KLIENT)
);
CREATE TABLE ZBIOR_WYPOZYCZEN(
ID_ZBIOR_WYPOZYCZEN INT PRIMARY KEY,
ID_PLYTY INT,
FOREIGN KEY (ID_PLYTY) REFERENCES PLYTY_DVD(ID_PLYTY),
ID_WYPOZYCZENIA INT,
FOREIGN KEY (ID_WYPOZYCZENIA) REFERENCES WYPOZYCZENIA(ID_WYPOZYCZENIA)
);

