CREATE TABLE PLYTA (
ID_PLYTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
TYTUL VARCHAR(100),
REZYSER VARCHAR(50),
ROK_WYDANIA DATE,
GATUNEK VARCHAR(20),
CENA_ZA_WYPOZYCZENIE DECIMAL(10,2)
);
CREATE TABLE KLIENT(
ID_KLIENT INT PRIMARY KEY AUTO_INCREMENT,
IMIE VARCHAR(30),
NAZWISKO VARCHAR(30),
ADRES VARCHAR(50),
NUMER_TEL VARCHAR(11),
EMAIL VARCHAR(30)
);
CREATE TABLE RACHUNEK(
ID_RACHUNEK INT PRIMARY KEY AUTO_INCREMENT,
DATA_WYSTAWINIA DATE,
OPLATA DECIMAL(10,2),
ID_KLIENT INT
);
ALTER TABLE RACHUNEK ADD FOREIGN KEY (ID_KLIENT) REFERENCES KLIENT(ID_KLIENT);

CREATE TABLE REZERWACJA(
ID_REZERWACJA INT PRIMARY KEY AUTO_INCREMENT,
ID_KLIENT INT,
ID_PLYTA INT,
DATA_ZAMOWIENIA DATE,
DATA_ODBIORU DATE,
DATA_ZWOROTU_PLANOWANA DATE,
OPLATA DECIMAL(10,3)
);
ALTER TABLE REZERWACJA ADD FOREIGN KEY (ID_KLIENT) REFERENCES KLIENT(ID_KLIENT);
ALTER TABLE REZERWACJA ADD FOREIGN KEY (ID_PLYTA) REFERENCES PLYTA(ID_PLYTA);
CREATE TABLE OPINIA(
  ID_OPINII INT PRIMARY KEY AUTO_INCREMENT, 
  ID_KLIENT INT,
  ID_PLYTA INT,
  OCENA INT,
  TRESC VARCHAR(255),
  FOREIGN KEY (ID_KLIENT) REFERENCES KLIENT(ID_KLIENT),
  FOREIGN KEY (ID_PLYTA) REFERENCES PLYTA(ID_PLYTA)
);
CREATE TABLE WYPOZYCZENIE(
  ID_WYPOZYCZENIE INT PRIMARY KEY AUTO_INCREMENT,
  DATA_WYPOZYCZENIA DATE,
  DATA_ZWROTU DATE, 
  OPLATA DECIMAL(10,2),
  ID_KLIENT INT,
  ID_PLYTA INT,
  FOREIGN KEY (ID_KLIENT) REFERENCES KLIENT(ID_KLIENT),
  FOREIGN KEY (ID_PLYTA) REFERENCES PLYTA(ID_PLYTA)
);
